In [1]:
import numpy as np
a=[1,2,3,4,5]
b=np.array(a)
c=np.array([1,3,5])
d = a[0:3] # list와 동일 방법
e=a*2 # [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
f=b*2 # [ 2  4  6  8 10]
k=np.array(12)
print(k)

12


In [7]:
a = np.array([1,2,3], dtype=int) # dtype = int, float, boo
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
print(a.ndim) # 2
print(a.shape) # (3,3)
print(a.dtype) # int


int32
2
(3, 3)
int32


In [16]:
a=np.ones((3,3), dtype=int) # [[1 1 1] [1 1 1] [1 1 1]]
b=np.zeros((3,3), dtype=int) # [[0 0 0] [0 0 0] [0 0 0]]
c=np.ones_like(a, dtype=int) # [[1 1 1] [1 1 1] [1 1 1]]
d=np.empty((2,2), dtype=int) # 초기화 없음 [[  622251514 -1991051952] [-1075023520  -937388200]]
e=np.empty_like(b, dtype=int) # 초기화 없음 [[1 1 1] [1 1 1] [1 1 1]]
f=np.identity(4, dtype=int) # [[1 0 0 0] [0 1 0 0] [0 0 1 0] [0 0 0 1]]
g=np.eye(4,4, k=1, dtype=int) # [[0 1 0 0] [0 0 1 0] [0 0 0 1] [0 0 0 0]]

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]]


In [29]:
a=np.arange(0,10, step=2)
b=np.linspace(0,10, num=5, endpoint=True, retstep=True) # 10을 마지막 값으로(True), 간격 표시(retstep)
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # 2x3
print(a[0:1, 0:2]) # [1,2]
c=a.reshape(9,1)
e=np.array([[1,2,3], [4,5,6], [7,8,9]], dtype=int)
f=np.ones(3, dtype=int)
g=np.cross(e,f) # cross product
h=np.dot(e,f) # dot product
# np.add np.subtract, np.multiply, np.divide np.power np.sqrt np.mod np.floor_divide np.logaddexp ...
# np.sin(a), np.cos() np.arcsin() np.sinh() np.deg2rad
# np.bitwise_and or xor not shift

[[1 2]]
[ 6 15 24]


In [31]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[1, 3], [2, 4]])
print(a*b)
ma=np.mat(a)
mb=np.mat(b)
print(ma*mb)

[[ 1  6]
 [ 6 16]]
[[ 5 11]
 [11 25]]
